# Generated by Django 2.2.5 on 2020-01-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='photo',
            field=models.URLField(blank=True),
        ),
    ]
